#!/bin/bash

set -e # halt on error
# set -x # echo cmds before executing
set -u # fail on undefined variable
set -o pipefail # force pipelines to fail on fail

export KEMAL_ENV=development
export PG_URL=postgresql://kpbb:kpbb@localhost:5433/kpbb?sslmode=require
export PORT=5000
export APP_DOMAIN=127.0.0.1
export APP_NAME=kpbb
export SPOOF_CFIPCC=us

# PATH="~/crystal/1.2.1-1/bin/:$PATH"
# crystal -v

source "$(dirname $0)/env" ".env.local"
# source ".env.local"
echo "KPBB_IMG_API: $KPBB_IMG_API"
crystal run src/watch_server.cr
